# Generated by Django 4.2.16 on 2026-05-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('accounts', '0005_user_counter_number_assigned_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='branches.branch'),
        ),
    ]
